= github-actions
Thomas W. Stütz, credits to Mr. Christian Aberger
1.0.0, 2021-03-17: How to use github-actions in project work @ HTL Leonding college
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
:toclevels: 5
:experimental: true
:linkattrs:   // so window="_blank" will be executed

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/security-lecture-notes/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/security-lecture-notes] ‏ ‏ ‎
icon:home[link=http://edufs.edu.htl-leonding.ac.at/~t.stuetz/hugo/2021/01/technology-notes/]
endif::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

----
Credits to Mr. Christian Aberger - this notes are based on his lecture @ HTL Leonding
----

== Overview - What we will do

. Create a Quarkus app providing a simple restful endpoint.
. This app will be pushed automatically to github
. Prepare the remote server for deploying the quarkus app (we will use an oracle vm instance)
. Create the gh-actions pipeline
. Create a service for starting the quarkus-app on the remote server

== Creating a Virtual Maschine Instance in Oracle Cloud

<<create-oravm.adoc#,Creating a Virtual Maschine Instance in Oracle Cloud>>


== Create a Simple Quarkus Application

<<create-quarkus-app.adoc#,Create a Quarkus Application>>

== Create a Continous Delivery Pipeline in gh-actions

<<gh-actions.adoc#,Create a yml-File>>



